/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package login2;

//import com.sun.istack.internal.logging.Logger;
import java.util.logging.Logger;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


/**
 *
 * @author Charlin
 */
public class loginMenu1 extends javax.swing.JFrame {

    /** Creates new form loginMenu */
    public loginMenu1() {
        initComponents();
        
        //centrado
        this.setLocationRelativeTo(null);
        
        Border closeMin = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK);
        
        jLabel3_closeButton.setBorder(closeMin);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_userName = new javax.swing.JTextField();
        jButton1_LogIn = new javax.swing.JButton();
        jPasswordField1_LogIn = new javax.swing.JPasswordField();
        jLabel3_closeButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USERNAME");

        jLabel2.setText("PASSWORD");

        jTextField1_userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_userNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_userNameFocusLost(evt);
            }
        });
        jTextField1_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_userNameActionPerformed(evt);
            }
        });

        jButton1_LogIn.setText("LOGIN");
        jButton1_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LogInActionPerformed(evt);
            }
        });

        jPasswordField1_LogIn.setText("Password");
        jPasswordField1_LogIn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1_LogInFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1_LogInFocusLost(evt);
            }
        });

        jLabel3_closeButton.setText("X");
        jLabel3_closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3_closeButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3_closeButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3_closeButtonMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)))
                        .addGap(106, 106, 106))
                    .addComponent(jLabel3_closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPasswordField1_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jTextField1_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3_closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jPasswordField1_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3_closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_closeButtonMouseEntered
       Border closeMin = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
       
       jLabel3_closeButton.setBorder(closeMin);
       jLabel3_closeButton.setForeground(Color.red);
    }//GEN-LAST:event_jLabel3_closeButtonMouseEntered

    private void jLabel3_closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_closeButtonMouseExited
        
        Border closeMin =  BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel3_closeButton.setBorder(closeMin);
       jLabel3_closeButton.setForeground(Color.black);
    }//GEN-LAST:event_jLabel3_closeButtonMouseExited

    private void jTextField1_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_userNameActionPerformed

    private void jTextField1_userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_userNameFocusGained
       
        if(jTextField1_userName.getText().trim().equals("Account")){
        
            jTextField1_userName.setText("");
            jTextField1_userName.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_jTextField1_userNameFocusGained

    private void jTextField1_userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_userNameFocusLost
       if(jTextField1_userName.getText().trim().equals("")||
           jTextField1_userName.getText().trim().equals("Account"))
       {
       
           
           jTextField1_userName.setText("Account");
           jTextField1_userName.setForeground(new Color(153,153,153));
       }              
    }//GEN-LAST:event_jTextField1_userNameFocusLost

    private void jButton1_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LogInActionPerformed
        PreparedStatement PreparedStatement;
        ResultSet ResultSet;
        
        
        String username = jTextField1_userName.getText();
        
        String password = String.valueOf(jPasswordField1_LogIn.getPassword());
        
        String query = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";
        
        if(username.trim().equals("username"))
        {
        JOptionPane.showMessageDialog(null, "Entre su username", "Username vacio", 2);
        
        }else if(password.trim().equals("password"))
        {
            JOptionPane.showMessageDialog(null,"entre su password", "password vacio",2);
            
        } else{
            try{
                PreparedStatement = sql_connector.getSqlConnection().prepareStatement(query);
                PreparedStatement.setString(1, username);
                PreparedStatement.setString(2, password);
                ResultSet = PreparedStatement.executeQuery();
                                
                if(ResultSet.next())       {
                Registro form = new Registro();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                //JOptionPane.showMessageDialog(null,"Correcto", "Login", 2);
                this.dispose();                              
                
                }else{
                    JOptionPane.showMessageDialog(null,"username invalido / password", "Login Error", 2);
                
                }      
            } catch(SQLException ex){
                
               Logger.getLogger(loginMenu1.class.getName()).log(Level.SEVERE,null, ex);
            }
        
        
        }
    }//GEN-LAST:event_jButton1_LogInActionPerformed

    private void jPasswordField1_LogInFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_LogInFocusGained
        String LogInPassword = String.valueOf(jPasswordField1_LogIn.getPassword());
        
        if( LogInPassword.trim().toLowerCase().equals("password"))
        {
        jPasswordField1_LogIn.setText("");
        jPasswordField1_LogIn.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField1_LogInFocusGained

    private void jPasswordField1_LogInFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_LogInFocusLost
       String LogInPassword = String.valueOf(jPasswordField1_LogIn.getPassword());
       
       if(LogInPassword.trim().equals("")||
          LogInPassword.trim().toLowerCase().equals("password"))
       {
        jPasswordField1_LogIn.setText("password");
        jPasswordField1_LogIn.setForeground(new Color(153, 153, 153));
        
           
       }
    }//GEN-LAST:event_jPasswordField1_LogInFocusLost

    private void jLabel3_closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3_closeButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3_closeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginMenu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_LogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_closeButton;
    private javax.swing.JPasswordField jPasswordField1_LogIn;
    private javax.swing.JTextField jTextField1_userName;
    // End of variables declaration//GEN-END:variables

}
